# Generated by Django 4.1.7 on 2023-04-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='priority',
            field=models.SmallIntegerField(default=0),
        ),
    ]
