# Generated by Django 4.1.7 on 2023-04-05 16:46

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0002_question_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersTestsResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tries', models.SmallIntegerField(default=0)),
                ('result', models.CharField(max_length=20)),
                ('results_details', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None), size=None)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.testpart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
