# Generated by Django 4.1.7 on 2023-02-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('content', models.TextField(default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
